_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
batch_size:
    value: 32
data_dir:
    value: data/deepfashion
device:
    value: cuda
epochs:
    value: 50
lr:
    value: 0.001
model:
    value: baseline
output_dir:
    value: outputs
