_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 80
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 80
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
backbone:
    value: resnet34
batch_size:
    value: 32
checkpoint_dir:
    value: checkpoints
data_root:
    value: data_deepfashion
dropout:
    value: 0.5
embedding_dim:
    value: 512
epochs:
    value: 50
experiment_name:
    value: darn_resnet34_baseline
label_smoothing:
    value: 0.1
lambda_attr:
    value: 1
lambda_rank:
    value: 1
log_dir:
    value: logs
lr:
    value: 0.0001
margin:
    value: 0.3
min_lr:
    value: 1e-06
num_workers:
    value: 4
scheduler:
    value: cosine
test_mode:
    value: false
visualize_every:
    value: 5
wandb:
    value: true
warmup_epochs:
    value: 5
weight_decay:
    value: 0.0001
