_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.9.20
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
batch_size:
    value: 64
data_dir:
    value: data/deepfashion
device:
    value: cpu
epochs:
    value: 2
lr:
    value: 0.001
output_dir:
    value: outputs
test_mode:
    value: true
wandb:
    value: true
