_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
backbone:
    value: vgg16
batch_size:
    value: 32
checkpoint_dir:
    value: checkpoints
data_root:
    value: data_deepfashion
embedding_dim:
    value: 512
epochs:
    value: 50
experiment_name:
    value: darn_baseline
lambda_attr:
    value: 1
lambda_rank:
    value: 1
log_dir:
    value: logs
lr:
    value: 0.0001
margin:
    value: 0.3
num_workers:
    value: 4
weight_decay:
    value: 0.0001
